# Numpy
******
NumPy(Numerical Python) 是 Python 语言的一个扩展程序库，支持大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。  
NumPy 是一个运行速度非常快的数学库，主要用于数组计算，包含：  
1. 一个强大的N维数组对象 ndarray  
2. 广播功能函数  
3. 整合 C/C++/Fortran 代码的工具  
4. 线性代数、傅里叶变换、随机数生成等功能  
Reference: [CS231n tutorial](https://cs231n.github.io/python-numpy-tutorial/)  
## 1. **Arrays**  
A numpy array is a grid of values, all of the same type, and is indexed by a tuple of nonnegative integers.  
The number of dimensions is the rank of the array; the shape of an array is a tuple of integers giving the size of the array along each dimension.

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(type(a))
print(a.shape)
print(a[0], a[1],  a[2])
a[0] = 123
print(a)

b  = np.array([[1, 2, 3],[4, 5, 6]])
print(b.shape)
print(b[0,2])

Numpy also has lots of functions to create arrays.

In [ ]:
import numpy as np

a = np.zeros((3, 3))
print(a)

b = np.ones((2,2))
print(b)

c = np.full((2,2), 7)
print(c)

d = np.eye(4)
print(d)

e = np.random.random((2,2))
print(e)

### Array indexing
Numpy provides several ways to index into arrays.  
#### 1. **Slicing**  
Since arrays may be multidimensional, you must specify a slice for each dimension of the array.

In [ ]:
import numpy as np
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)

# Use slicing to pull out the subarray consisting of the first 2 rows and columns 1 and 2;
# b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print(b)

# NOTICE: A slice of an array is a view into the same data, so modifying it will modify the original array.
print(a[0, 1])    # Prints "2"
b[0, 0] = 100     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])    # Prints "100"

row_r1 = a[1, :]
row_r2 = a[1:2, :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)

col_r1 = a[:, 1]
col_r2 = a[:, 1:2]
print(col_r1, col_r1.shape)
print(col_r2, col_r2.shape)

#### 2. **Integer array indexing**  
Integer array indexing allows you to construct arbitrary arrays using the data from another array. 

In [ ]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

# An example of integer array indexing.
b = a[[0, 1, 2], [0, 1, 0]]
print(b, b.shape)

# The above example of integer array indexing is equivalent to this:
c = np.array([a[0, 0], a[1, 1], a[2, 0]])
d = [a[0, 0], a[1, 1], a[2, 0]]
print(c, type(c), c.shape)
print(d, type(d))

# When using integer array indexing, you can reuse the same element from the source array:
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

One useful trick with integer array indexing is selecting or mutating one element from each row of a matrix:

In [8]:
import numpy as np

# Create a new array from which we will select elements
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])

print(a)  # Create an array "([[ 1,  2,  3],
          #                    [ 4,  5,  6],
          #                    [ 7,  8,  9],
          #                    [10, 11, 12]])"

# Create an array of indices
b = np.array([0, 2, 0])

# Select one element from each row of a using the indices in b
print(a[np.arange(3), b])

# Mutate one element from each row of a using the indices in b
a[np.arange(3), b] += 10

print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[1 6 7]
[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 11 12]]


#### 3. **Boolean array indexing**  
Boolean array indexing lets you pick out arbitrary elements of an array.

In [9]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])

bool_idx = (a > 2)
print(bool_idx)
print(a[bool_idx])
print(a[a > 2])

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
